// Adam McCutcheon

const validCities = [
    // CA Cities
    "29 Palms",
    "Acampo",
    "Acton",
    "Adelanto",
    "Adin",
    "Aerial Acres",
    "Afton",
    "Agoura",
    "Agoura Hills",
    "Agua Dulce",
    "Aguanga",
    "Ahwahnee",
    "Alamo Oaks",
    "Alberhill",
    "Albion",
    "Alhambra",
    "Aliso Viejo",
    "Almanor",
    "Alpine",
    "Alpine Forest",
    "Alta Loma",
    "Altadena",
    "Alturas",
    "Amador City",
    "American Canyon",
    "Amsterdam",
    "Anaheim",
    "Anaheim Hills",
    "Anderson",
    "Angels Camp",
    "Angelus Oaks",
    "Angwin",
    "Annapolis",
    "Antelope",
    "Antelope Acres",
    "Antioch",
    "Anza",
    "Apache Junction",
    "Apple Valley",
    "Arbuckle",
    "Arcadia",
    "Arleta",
    "Arnold",
    "Arrowbear",
    "Arroyo Grande",
    "Artesia",
    "Artois",
    "Arvin",
    "Atascadero",
    "Athens",
    "Atwater",
    "Atwater Village",
    "Auberry",
    "Auburn",
    "Avalon",
    "Avenal",
    "Avila Beach",
    "Avondale",
    "Azusa",
    "Baker",
    "Bakersfield",
    "Baldwin Hills",
    "Baldwin Park",
    "Ballard",
    "Ballico",
    "Bangor",
    "Banning",
    "Bard",
    "Bardsdale",
    "Barstow",
    "Bass Lake",
    "Bassett",
    "Bay Point",
    "Bayliss",
    "Baywood Park",
    "Bear Reservoir",
    "Bear Valley",
    "Bear Valley Springs",
    "Beaumont",
    "Beckwourth",
    "Bel Air",
    "Belden",
    "Bell",
    "Bell Canyon",
    "Bell Gardens",
    "Bella Vista",
    "Bellflower",
    "Berkeley",
    "Bermuda Dunes",
    "Berry Creek",
    "Beverly Hills",
    "Big Bar",
    "Big Bear",
    "Big Bend",
    "Big Mountain Ridge",
    "Big Pines",
    "Big River",
    "Big Rock",
    "Biggs",
    "Biola",
    "Blairsden",
    "Bloomington",
    "Blue Jay",
    "Blue Lake",
    "Blythe",
    "Bodega",
    "Bodega Bay",
    "Bodfish",
    "Bombay Beach",
    "Bonadelle Ranchos",
    "Bonds Corner",
    "Bonita",
    "Bonsall",
    "Boonville",
    "Boron",
    "Borrego Springs",
    "Boulder City",
    "Boulevard",
    "Bradbury",
    "Brawley",
    "Brea",
    "Brentwood",
    "Brentwood (CC)",
    "Browns Valley",
    "Brownsville",
    "Brundage",
    "Brush Creek",
    "Buckhorn",
    "Buckingham Park",
    "Bucks Lake",
    "Buellton",
    "Buena Park",
    "Bullhead City",
    "Burbank",
    "Burlington",
    "Burney",
    "Burson",
    "Butte City",
    "Butte Meadows",
    "Butte Valley",
    "Butterfly Valley",
    "Buttonwillow",
    "Cabazon",
    "Cahuenga Pass",
    "Calabasas",
    "Calabasas Highlands",
    "Calabasas Park",
    "Caldors Corner",
    "Calexico",
    "Caliente",
    "California City",
    "Calimesa",
    "Calipatria",
    "Calistoga",
    "Calpella",
    "Calpine",
    "Camarillo",
    "Cambria",
    "Cameron Park",
    "Camino",
    "Campbellville",
    "Campo",
    "Camptonville",
    "Canby",
    "Canoga Park",
    "Cantil",
    "Canyon Areas",
    "Canyon Country",
    "Canyon Dam",
    "Canyon Lake",
    "Capay",
    "Carbondale",
    "Cardiff by the Sea",
    "Carefree",
    "Caribou",
    "Carlsbad",
    "Carmel Valley",
    "Carmichael",
    "Carnelian Bay",
    "Carpinteria",
    "Carson",
    "Carson City",
    "Caruthers",
    "Casa Conejo",
    "Cascade",
    "Casmalia",
    "Castaic",
    "Castellammare",
    "Castro Valley",
    "Cathedral City",
    "Catheys Valley",
    "Cayucos",
    "Cazadero",
    "Cedar Glen",
    "Cedarpines Park",
    "Ceres",
    "Cerritos",
    "Challenge",
    "Chandler",
    "Channel Islands",
    "Beach",
    "Charter Oak",
    "Chatsworth",
    "Cherokee",
    "Cherry Valley",
    "Chester",
    "Cheviot Hills",
    "Chico",
    "Chilcoot",
    "China Lake",
    "Chino",
    "Chino Hills",
    "Cholame",
    "Chowchilla",
    "Chula Vista",
    "Citrus Heights",
    "City Of Industry",
    "City Ranch",
    "City Terrace",
    "Clairemont Mesa",
    "Claremont",
    "Clear Creek",
    "Clearlake",
    "Clearlake Highlands",
    "Clearlake Oaks",
    "Clearlake Park",
    "Clio",
    "Clipper Mills",
    "Cloverdale",
    "Clovis",
    "Coachella",
    "Coalinga",
    "Coarsegold",
    "Cobb",
    "Coffee",
    "Cohasset",
    "Cold Springs",
    "College City",
    "Coloma",
    "Colton",
    "Colusa",
    "Commerce",
    "Compton",
    "Concord",
    "Concow",
    "Coolidge Springs",
    "Coos Bay",
    "Copperopolis",
    "Corcoran",
    "Cornell",
    "Corning",
    "Corona",
    "Corona del Mar",
    "Coronado",
    "Costa Mesa",
    "Cotati",
    "Coto de Caza",
    "Cottonwood",
    "Cottonwood Canyon",
    "Coulterville",
    "Country Club Park",
    "County - Los Angeles",
    "Covelo",
    "Covina",
    "Cowan Heights",
    "Crenshaw",
    "Crescent Mills",
    "Cressey",
    "Crestline",
    "Creston",
    "Cromberg",
    "Crows Landing",
    "Cudahy",
    "Cuesta By The Sea",
    "Culver City",
    "Cupertino",
    "Cutler",
    "Cuyama",
    "Cypress",
    "Cypress Park",
    "Dairyville",
    "Dales",
    "Dana Point",
    "Davis",
    "Dayton",
    "Del Cerro",
    "Del Kern",
    "Del Mar",
    "Del Rey",
    "Del Sur",
    "Delano",
    "Delevan",
    "Delhi",
    "Delleker",
    "Denair",
    "DeSabla",
    "Descanso",
    "Desert Center",
    "Desert Hot Springs",
    "Desert Lake",
    "Desert Shores",
    "Devore",
    "Di Giorgio",
    "Diamond Bar",
    "Diamond Springs",
    "Dillon Beach",
    "Dinuba",
    "Discovery Bay",
    "Dixie Valley",
    "Dixon",
    "Dobbins",
    "Dorris",
    "Dos Palos",
    "Douglas City",
    "Dove Canyon",
    "Downey",
    "Downieville",
    "Doyle",
    "Drytown",
    "Duarte",
    "Dublin",
    "Dulzura",
    "Dunnigan",
    "Dunsmuir",
    "Durham",
    "Eagle Park",
    "Eagle Rock",
    "East Bakersfield",
    "East Gridley",
    "East Los Angeles",
    "East San Diego",
    "Eastvale",
    "Echo Park",
    "Edison",
    "Edward",
    "Edwards",
    "El Cajon",
    "El Camino",
    "El Centro",
    "El Cerrito",
    "El Cerrito (CC)",
    "El Dorado",
    "El Dorado Hills",
    "El Mirage",
    "El Monte",
    "El Nido",
    "El Portal",
    "El Porto",
    "El Rio",
    "El Segundo",
    "El Sereno",
    "El Sobrante",
    "Elk Creek",
    "Elk Grove",
    "Empire",
    "Encinitas",
    "Encino",
    "Escalon",
    "Escondido",
    "Esparto",
    "Estrella",
    "Eureka",
    "Exeter",
    "Fair Oaks Ranch",
    "Fair Play",
    "Fairfield",
    "Fairmead",
    "Fairmont",
    "Fallbrook",
    "Falling Springs",
    "Faria Beach",
    "Farmersville",
    "Fawnskin",
    "Feather Falls",
    "Felicity",
    "Fellows",
    "Fernwood",
    "Fiddletown",
    "Fillmore",
    "Finley",
    "Firebaugh",
    "Fish Camp",
    "Flagstaff",
    "Florence",
    "Flournoy",
    "Folsom",
    "Fontana",
    "Foothill Ranch",
    "Forbestown",
    "Foreign Country",
    "Forest Falls",
    "Forest Ranch",
    "Foresthill",
    "Forestville",
    "Forrest Park",
    "Fort Bragg",
    "Foster City",
    "Fountain Valley",
    "Four Corners",
    "Four Points",
    "Fowler",
    "Fox Hills",
    "Frazier Park",
    "Fremont",
    "Fremont Valley",
    "French Camp",
    "French Gulch",
    "French Valley",
    "Frenchtown",
    "Fresno",
    "Friant",
    "Fruitvale",
    "Fruto",
    "Fullerton",
    "Galt",
    "Garden Grove",
    "Garden Valley",
    "Gardena",
    "Garey",
    "Garlock",
    "Garner Valley",
    "Garnet",
    "Garvanza",
    "Gaviota",
    "Genesee",
    "Georgetown",
    "Gerber",
    "Gilbert",
    "Gilroy",
    "Glassell Park",
    "Glen Avon",
    "Glen Helen",
    "Glen Ivy",
    "Glenbrook",
    "Glencoe",
    "Glendale",
    "Glendora",
    "Glenhaven",
    "Glenn",
    "Glennville",
    "Glenview",
    "Golden Hills",
    "Goleta",
    "Good Hope",
    "Goodyears Bar",
    "Gorman",
    "Graeagle",
    "Granada Hills",
    "Grand Terrace",
    "Grapevine",
    "Grass Valley",
    "Greeley",
    "Greeley Hill",
    "Green Valley",
    "Green Valley Lake",
    "Greenacres",
    "Greenville",
    "Gridley",
    "Grizzly Flats",
    "Groveland",
    "Grover Beach",
    "Guadalupe",
    "Gualala",
    "Guatay",
    "Guerneville",
    "Guinda",
    "Gustine",
    "Hacienda Hts",
    "Hallelujah Junction",
    "Hamilton Branch",
    "Hamilton City",
    "Hancock Park",
    "Hanford",
    "Harbor City",
    "Harmony",
    "Havasu City",
    "Havilah",
    "Hawaiian Gardens",
    "Hawthorne",
    "Hayfork",
    "Hayward",
    "Healdsburg",
    "Heber",
    "Helendale",
    "Hemet",
    "Henderson",
    "Herald",
    "Herlong",
    "Hermosa Beach",
    "Hesperia",
    "Hidden Hills",
    "Hidden Valley",
    "Hidden Valley Lake",
    "Highgrove",
    "Highland",
    "Highland Park",
    "Highland Springs",
    "Hillcrest Center",
    "Hilltop",
    "Hilmar",
    "Hollister",
    "Hollydale",
    "Hollywood",
    "Hollywood Hills",
    "Hollywood Hills East",
    "Holtville",
    "Homeland",
    "Homewood",
    "Honcut",
    "Honolulu",
    "Hooker",
    "Hopland",
    "Hornbrook",
    "Hornitos",
    "Horse Creek",
    "Hughson",
    "Huntington Beach",
    "Huntington Park",
    "Huron",
    "Hyde Park",
    "Idyllwild",
    "Igo",
    "Imperial",
    "Imperial Beach",
    "Imperial City",
    "Incline Village",
    "Indian Falls",
    "Indian Hills",
    "Indian Springs",
    "Indian Valley",
    "Indian Wells",
    "Indio",
    "Inglewood",
    "Inskip",
    "Inyokern",
    "Ione",
    "Irvine",
    "Irwindale",
    "Isla Vista",
    "Isleton",
    "Ivanhoe",
    "Jackson",
    "Jacumba",
    "Jamestown",
    "Jamul",
    "Janesville",
    "Jefferson Park",
    "Johannesburg",
    "Johnson Valley",
    "Johnsville",
    "Jonesville",
    "Joshua Hills",
    "Joshua Tree",
    "Julian",
    "Juniper Flats",
    "Juniper Hills",
    "Jupiter",
    "Kagel Canyon",
    "Keddie",
    "Keene",
    "Kelsey",
    "Kelseyville",
    "Kerman",
    "Kernville",
    "Keswick",
    "Keyes",
    "Kings Beach",
    "Kingsburg",
    "Kirkwood",
    "Knights Landing",
    "Komandorski Village",
    "Kramer Junction",
    "La Canada Flintridge",
    "La Conchita",
    "La Crescenta",
    "La Grange",
    "La Habra",
    "La Habra Heights",
    "La Jolla",
    "La Mesa",
    "La Mirada",
    "La Palma",
    "La Porte",
    "La Puente",
    "La Quinta",
    "La Sierra",
    "La Tuna Canyon",
    "La Verne",
    "Ladera Heights",
    "Ladera Ranch",
    "Lafayette",
    "Laguna Beach",
    "Laguna Hills",
    "Laguna Niguel",
    "Laguna Woods",
    "Lake Almanor",
    "Lake Almanor Peninsula",
    "Lake Almanor West",
    "Lake Arrowhead",
    "Lake Balboa",
    "Lake Camanche",
    "Lake Don Pedro",
    "Lake Elizabeth",
    "Lake Elsinore",
    "Lake Forest",
    "Lake Havasu",
    "Lake Hollywood",
    "Lake Hughes",
    "Lake Isabella",
    "Lake Los Angeles",
    "Lake Mathews",
    "Lake Nacimiento",
    "Lake Sherwood",
    "Lakehead",
    "Lakeport",
    "Lakeside",
    "Lakeview",
    "Lakeview Terrace",
    "Lakewood",
    "Lamont",
    "Lancaster",
    "Landers",
    "Lang",
    "LaPorte",
    "Las Vegas",
    "Lathrop",
    "Laton",
    "Laughlin",
    "Lawndale",
    "Laytonville",
    "Le Grand",
    "Lebec",
    "Leggett",
    "Leimert Park",
    "Lemon Grove",
    "Lemoore",
    "Lennox",
    "Leona Valley",
    "Lincoln Heights",
    "Linda",
    "Linda Vista",
    "Linden",
    "Lindsay",
    "Litchfield",
    "Little Rock",
    "Live Oak",
    "Livermore",
    "Livingston",
    "Llano",
    "Loch Lomond",
    "Lockeford",
    "Lodi",
    "Lodoga",
    "Logan Heights",
    "Loma Linda",
    "Loma Rica",
    "Lomita",
    "Lomo",
    "Lompoc",
    "Long Barn",
    "Long Beach",
    "Longview",
    "Lookout",
    "Loraine",
    "Los Alamitos",
    "Los Alamos",
    "Los Altos",
    "Los Angeles",
    "Los Banos",
    "Los Feliz",
    "Los Molinos",
    "Los Nietos",
    "Los Olivos",
    "Los Osos",
    "Lost City",
    "Lost Hills",
    "Lotus",
    "Lower Lake",
    "Loyalton",
    "Lucerne",
    "Lucerne Valley",
    "Lynwood",
    "Lytle Creek",
    "Macdoel",
    "Madeline",
    "Madera",
    "Madera Acres",
    "Madera Ranchos",
    "Magalia",
    "Malibu",
    "Mammoth Lakes",
    "Manhattan Beach",
    "Manteca",
    "Manton",
    "Mar Vista",
    "Maricopa",
    "Marina",
    "Marina del Rey",
    "Mariposa",
    "Martell",
    "Marysville",
    "Maxwell",
    "Maybe",
    "Mayfair",
    "Maywood",
    "McCloud",
    "Mcfarland",
    "Mckittrick",
    "Mead Valley",
    "Meadow Valley",
    "Meadowbrook",
    "Meadows Field",
    "Mecca",
    "Meiners Oaks",
    "Mendocino",
    "Mendota",
    "Menifee",
    "Mentone",
    "Merced",
    "Merced Falls",
    "Meridian",
    "Mesa",
    "Mettler",
    "Middleton",
    "Middletown",
    "Midpines",
    "Midway City",
    "Milford",
    "Mill Creek",
    "Mill Valley",
    "Millville",
    "Mineral",
    "Mint Canyon",
    "Mira Loma",
    "Mira Mesa",
    "Mira Monte",
    "Miraleste",
    "Miramar",
    "Miramonte",
    "Mission Hills (San Diego)",
    "Mission Hills (San Fernando)",
    "Mission Hills Santa",
    "Barbara",
    "Mission Valley",
    "Mission Viejo",
    "Modesto",
    "Modjeska Canyon",
    "Mohawk",
    "Mojave",
    "Mokelumne Hill",
    "Moneta",
    "Monolith",
    "Monrovia",
    "Montague",
    "Montclair",
    "Monte Nido",
    "Montebello",
    "Montecito",
    "Montecito Heights",
    "Monterey Hills",
    "Monterey Park",
    "Montpelier",
    "Montrose",
    "Moorpark",
    "Moreno Valley",
    "Morgan Hill",
    "Morningside Park",
    "Morongo Valley",
    "Morro Bay",
    "Mount Aukum",
    "Mount Laguna",
    "Mount Olympus",
    "Mount Signal",
    "Mount Washington",
    "Mountain Center",
    "Mountain Home",
    "Village",
    "Mountain Mesa",
    "Mountain Ranch",
    "Mountain Valley",
    "Mt Baldy",
    "Murphys",
    "Murrieta",
    "Napa",
    "National City",
    "Needles",
    "Neenach",
    "Nelson",
    "Nevada",
    "Nevada City",
    "New Auberry",
    "Newberry Springs",
    "Newbury Park",
    "Newhall",
    "Newman",
    "Newport Beach",
    "Newport Coast",
    "Nice",
    "Nicolaus",
    "Niland",
    "Nipomo",
    "Norco",
    "Nord",
    "North Edwards",
    "North Fork",
    "North Highlands",
    "North Hills",
    "North Hollywood",
    "North Las Vegas",
    "North Park (San Diego)",
    "North Shore",
    "North Tustin",
    "North Wawona",
    "Northridge",
    "Norwalk",
    "Norwood Village",
    "Novato",
    "Nuevo/Lakeview",
    "Oak Glen",
    "Oak Hills",
    "Oak Park",
    "Oak Run",
    "Oak View",
    "Oakdale",
    "Oakhurst",
    "Oakland",
    "Oakley",
    "Oaks",
    "Oasis",
    "Oban",
    "Ocean Beach (San Diego)",
    "Ocean Park",
    "Oceano",
    "Oceanside",
    "Ocotillo",
    "Oildale",
    "Ojai",
    "Olancha",
    "Old Canyon",
    "Old Forbestown",
    "Old Station",
    "Old Town (San Diego)",
    "Olive",
    "Olive View",
    "Olivehurst",
    "Olympia",
    "Olympic Village",
    "Omo Ranch",
    "O Neals",
    "Ono",
    "Ontario",
    "Onyx",
    "Orange",
    "Orange Cove",
    "Orange Park Acres",
    "Orangevale",
    "Orcutt",
    "Oregon House",
    "Orland",
    "Orosi",
    "Oroville",
    "Ortega Mountain",
    "Otay Mesa",
    "Oxnard",
    "Pacific Beach (San Diego)",
    "Pacific Grove",
    "Pacific Palisades",
    "Pacifica",
    "Pacoima",
    "Pahrump",
    "Pala",
    "Palermo",
    "Palisades Heights",
    "Palm Desert",
    "Palm Springs",
    "Palmdale",
    "Palms",
    "Palo Cedro",
    "Palo Verde",
    "Paloma",
    "Palomar Mountain",
    "Palos Verdes Estates",
    "Palos Verdes Peninsula - Unincorporated",
    "Panorama City",
    "Paradise",
    "Paradise Hills",
    "Paramount",
    "Park Hills Heights",
    "Parker",
    "Parklabrea",
    "Parlier",
    "Pasadena",
    "Paskenta",
    "Paso Robles",
    "Patterson",
    "Pauma Valley",
    "Paxton",
    "Paynes Creek",
    "Pearblossom",
    "Pearland",
    "Pearsonville",
    "Pebble Beach",
    "Pedley",
    "Penn Valley",
    "Penngrove",
    "Peoria",
    "Perris",
    "Petaluma",
    "Phelan",
    "Phillips Ranch",
    "Phoenix",
    "Pico",
    "Pico Rivera",
    "Pike",
    "Pine Cove",
    "Pine Grove",
    "Pine Mountain",
    "Pine Valley",
    "Pinedale",
    "Pinetree",
    "Pinole",
    "Pinon Hills",
    "Pinyon Pines",
    "Pioneer",
    "Pioneertown",
    "Piru",
    "Pismo Beach",
    "Pittsburg",
    "Placentia",
    "Placerville",
    "Plainsburg",
    "Planada",
    "Platina",
    "Playa del Rey",
    "Playa Vista",
    "Plymouth",
    "Point Dume",
    "Point Loma",
    "Point Mugu",
    "Pollock Pines",
    "Pomona",
    "Pond",
    "Pope Valley",
    "Port Hueneme",
    "Porterville",
    "Portola",
    "Portola Hills",
    "Potrero",
    "Potter Valley",
    "Poway",
    "Pozo",
    "Prather",
    "Prattville",
    "Prescott",
    "Princeton",
    "Proberta",
    "Pumpkin Center",
    "Quail Valley",
    "Quartz Hill",
    "Quincy",
    "Rackerby",
    "Rail Road Flat",
    "Rainbow",
    "Ramona",
    "Ranchita",
    "Rancho Bernardo (San Diego)",
    "Rancho California",
    "Rancho Cordova",
    "Rancho Cucamonga",
    "Rancho Dominguez",
    "Rancho Mirage",
    "Rancho Murieta",
    "Rancho Palos",
    "Verdes",
    "Rancho Park",
    "Rancho Penasquitos",
    "Rancho Santa Fe",
    "Rancho Santa",
    "Margarita",
    "Rancho Tehama",
    "Reserve",
    "Rancho Vista",
    "Randsburg",
    "Ravendale",
    "Ravenna",
    "Raymond",
    "Red Bank",
    "Red Bluff",
    "Redding",
    "Redlands",
    "Redman",
    "Redondo Beach",
    "Redwood City",
    "Redwood Valley",
    "Reedley",
    "Reno",
    "Reseda",
    "Rialto",
    "Rich Bar",
    "Richfield",
    "Richvale",
    "Ridgecrest",
    "Rimforest",
    "Rio Linda",
    "Ripon",
    "Ritter Ranch",
    "River Kern",
    "River Pines",
    "Riverbank",
    "Riverdale",
    "Riverside",
    "Riviera",
    "Robbins",
    "Robinson Mills",
    "Robinsons Corner",
    "Rocklin",
    "Rohnert Park",
    "Rolling Hills",
    "Rolling Hills Estates",
    "Romoland",
    "Romona",
    "Roosevelt",
    "Rosamond",
    "Rose Park",
    "Rosemead",
    "Roseville",
    "Rosewood",
    "Rossmoor",
    "Rough and Ready",
    "Round Mountain",
    "Rowland Heights",
    "Rubidoux",
    "Running Springs",
    "Area",
    "Ruth",
    "Sacramento",
    "Sage",
    "Salida",
    "Salinas",
    "Salton City",
    "Salton Sea",
    "Salton Sea Beach",
    "San Andreas",
    "San Bernardino",
    "San Buenaventura",
    "San Carlos",
    "San Clemente",
    "San Diego",
    "San Dimas",
    "San Fernando",
    "San Francisco",
    "San Gabriel",
    "San Geronimo",
    "San Jacinto",
    "San Joaquin",
    "San Jose",
    "San Juan Capistrano",
    "San Leandro",
    "San Luis Obispo",
    "San Luis Rey",
    "San Marcos",
    "San Marino",
    "San Miguel",
    "San Pablo",
    "San Pedro",
    "San Rafael",
    "San Ramon",
    "San Simeon",
    "San Ysidro",
    "Sandberg",
    "Sanger",
    "Santa Ana",
    "Santa Ana Heights",
    "Santa Barbara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Fe Springs",
    "Santa Margarita",
    "Santa Maria",
    "Santa Monica",
    "Santa Nella",
    "Santa Paula",
    "Santa Rosa",
    "Santa Rosa (SON)",
    "Santa Ynez",
    "Santa Ysabel",
    "Santee",
    "Saratoga Springs",
    "Saticoy",
    "Saugus",
    "Sawtelle",
    "Scotts Valley",
    "Scottsdale",
    "Scripps Miramar",
    "Seal Beach",
    "Sebastopol",
    "Sedco",
    "Sedona",
    "Seeley",
    "Selma",
    "Seneca",
    "Sequim",
    "Shadow Hills",
    "Shafter",
    "Shandon",
    "Shasta",
    "Shasta Lake",
    "Shaver Lake",
    "Shelter Cove",
    "Sherman Oaks",
    "Shingle Springs",
    "Shingletown",
    "Sierra City",
    "Sierra Madre",
    "Sierraville",
    "Signal Hill",
    "Silver Lake",
    "Silverado Canyon",
    "Simi Valley",
    "Simmler",
    "Sisquoc",
    "Sky Valley",
    "Sleepy Valley",
    "Sloat",
    "Sloughhouse",
    "Smartsville",
    "Smoke Tree Valley",
    "Snelling",
    "Soda Bay",
    "Solana Beach",
    "Soledad",
    "Solvang",
    "Somerset",
    "Somis",
    "Sonoma",
    "Sonora",
    "Sorrento",
    "South Dos Palos",
    "South El Monte",
    "South Gate",
    "South Lake Tahoe",
    "South Pasadena",
    "South San Francisco",
    "South San Gabriel",
    "South San Jose Hills",
    "South Yuba",
    "Sparks",
    "Spring Garden",
    "Spring Valley",
    "Springville",
    "Squaw Valley",
    "St. Helena",
    "Stallion Springs",
    "Standish",
    "Stanton",
    "Stateline",
    "Stevenson Ranch",
    "Stevinson",
    "Stirling City",
    "Stockdale",
    "Stockton",
    "Stonyford",
    "Storrie",
    "Strawberry",
    "Strawberry Valley",
    "Studio City",
    "Sugar Loaf",
    "Sulpher Springs",
    "Summerland",
    "Sun City",
    "Sun Valley",
    "Sun Village",
    "Sunland",
    "Sunnybrook",
    "Sunnymead",
    "Sunset Beach",
    "Surf",
    "Surfside",
    "Surprise",
    "Susanville",
    "Sutter",
    "Sutter Creek",
    "Sutter Hill",
    "Sylmar",
    "Sylvia Park",
    "Taft",
    "Tahoe City",
    "Tahoe Vista",
    "Tahoma",
    "Tarzana",
    "Taylorsville",
    "Tecate",
    "Tehachapi",
    "Tehama",
    "Temecula",
    "Tempe",
    "Temple City",
    "Templeton",
    "Termo",
    "Thermal",
    "Thermalito",
    "Thornton",
    "Thousand Oaks",
    "Thousand Palms",
    "Tierrasanta",
    "Tobin",
    "Tollhouse",
    "Toluca Lake",
    "Topanga",
    "Topanga Park",
    "Torrance",
    "Trabuco Canyon",
    "Tracy",
    "Traver",
    "Trigo",
    "Trinity Center",
    "Trona",
    "Tropico Village",
    "Trousdale Estates",
    "Truckee",
    "Tucson",
    "Tujunga",
    "Tulare",
    "Tupman",
    "Turlock",
    "Tustin",
    "Tuttletown",
    "Twain",
    "Twain Harte",
    "Twin Peaks",
    "Ukiah",
    "Union City",
    "Universal City",
    "University City",
    "Upland",
    "Upper Lake",
    "Vacaville",
    "Val Verde Park",
    "Valencia",
    "Valinda",
    "Vallecito",
    "Vallejo",
    "Valley Center",
    "Valley Glen",
    "Valley Springs",
    "Valley Village",
    "Valyermo",
    "Van Nuys",
    "Vandenburg Village",
    "Vasquez Rocks",
    "Venice",
    "Ventura",
    "Verdi",
    "Verdugo City",
    "Vernon",
    "Victor Valley",
    "Victorville",
    "View Park",
    "Villa Park",
    "Vina",
    "Vinton",
    "Viola",
    "Virgilia",
    "Visalia",
    "Vista",
    "Vista Park",
    "Volcano",
    "Wallace",
    "Walnut",
    "Walnut Park",
    "Warner Springs",
    "Wasco",
    "Waterford",
    "Wawona",
    "Weaverville",
    "Weed",
    "Weldon",
    "West Covina",
    "West Hills",
    "West Hollywood",
    "West Los Angeles",
    "West Point",
    "Westchester",
    "Westlake Village",
    "Westminster",
    "Westmorland",
    "Westwood",
    "Westwood - Century City",
    "Wheatland",
    "Whiskeytown",
    "Whispering Pines",
    "Whitely Gardens",
    "Whitewater",
    "Whitmore",
    "Whittier",
    "Wilcox Valley",
    "Wilderville",
    "Wildomar",
    "Wildwood",
    "Williams",
    "Willits",
    "Willow Creek",
    "Willow Springs",
    "Willowbrook",
    "Willows",
    "Wilmington",
    "Wilseyville",
    "Wilson Valley",
    "Wilsona Gardens",
    "Wilton",
    "Winchester",
    "Windsor",
    "Windsor Hills",
    "Winnetka",
    "Winterhaven",
    "Winton",
    "Wishon",
    "Wofford Heights",
    "Wonder Valley",
    "Woodcrest",
    "Woodlake",
    "Woodland Hills",
    "Woodside Village",
    "Woody",
    "Wrightwood",
    "Wyandotte",
    "Yankee Hill",
    "Yorba Linda",
    "Yorkville",
    "Yosemite",
    "Yreka",
    "Yuba City",
    "Yucaipa",
    "Yucca Valley",
    "Yuma",
    "Zephyr Cove",
    // TX Cities
    "Abbott",
    "Abernathy",
    "Abilene",
    "Ace",
    "Ackerly",
    "Addison",
    "Adkins",
    "Adrian",
    "Afton",
    "Agua Dulce",
    "Aiken",
    "Alamo",
    "Alanreed",
    "Alba",
    "Albany",
    "Aledo",
    "Alice",
    "Alief",
    "Allen",
    "Alleyton",
    "Allison",
    "Alpine",
    "Altair",
    "Alto",
    "Alvarado",
    "Alvin",
    "Alvord",
    "Amarillo",
    "Amherst",
    "Anahuac",
    "Anderson",
    "Andrews",
    "Angleton",
    "Angus",
    "Anna",
    "Annona",
    "Anson",
    "Anthony",
    "Anton",
    "Apple Springs",
    "Aquilla",
    "Aransas Pass",
    "Archer City",
    "Argyle",
    "Arlington",
    "Armstrong",
    "Arp",
    "Art",
    "Artesia Wells",
    "Arthur City",
    "Asherton",
    "Aspermont",
    "Atascosa",
    "Athens",
    "Atlanta",
    "Aubrey",
    "Austin",
    "Austwell",
    "Avalon",
    "Avery",
    "Avinger",
    "Avoca",
    "Axtell",
    "Azle",
    "Bacliff",
    "Bagwell",
    "Bailey",
    "Baird",
    "Ballinger",
    "Balmorhea",
    "Bandera",
    "Bangs",
    "Banquete",
    "Bardwell",
    "Barker",
    "Barksdale",
    "Barnhart",
    "Barry",
    "Barstow",
    "Bartlett",
    "Bastrop",
    "Batesville",
    "Batson",
    "Bay City",
    "Bayside",
    "Baytown",
    "Beasley",
    "Beaumont",
    "Bebe",
    "Beckville",
    "Bedford",
    "Bedias",
    "Beeville",
    "Bellaire",
    "Bellevue",
    "Bells",
    "Bellville",
    "Belmont",
    "Belton",
    "Ben Bolt",
    "Ben Franklin",
    "Ben Wheeler",
    "Benavides",
    "Bend",
    "Benjamin",
    "Berclair",
    "Bergheim",
    "Bertram",
    "Big Bend National Park",
    "Big Lake",
    "Big Sandy",
    "Big Spring",
    "Big Wells",
    "Bigfoot",
    "Bishop",
    "Bivins",
    "Blackwell",
    "Blanco",
    "Blanket",
    "Bledsoe",
    "Bleiblerville",
    "Blessing",
    "Bloomburg",
    "Blooming Grove",
    "Bloomington",
    "Blossom",
    "Blue Ridge",
    "Bluegrove",
    "Bluff Dale",
    "Bluffton",
    "Blum",
    "Boerne",
    "Bogata",
    "Boling",
    "Bon Wier",
    "Bonham",
    "Booker",
    "Borger",
    "Bovina",
    "Bowie",
    "Boyd",
    "Boys Ranch",
    "Brackettville",
    "Brady",
    "Brandon",
    "Brashear",
    "Brazoria",
    "Breckenridge",
    "Bremond",
    "Brenham",
    "Bridge City",
    "Bridgeport",
    "Briggs",
    "Briscoe",
    "Broaddus",
    "Bronson",
    "Bronte",
    "Brookeland",
    "Brookesmith",
    "Brookshire",
    "Brookston",
    "Brownfield",
    "Brownsboro",
    "Brownsville",
    "Brownwood",
    "Bruceville",
    "Bruni",
    "Bryan",
    "Bryson",
    "Buchanan Dam",
    "Buckholts",
    "Buda",
    "Buffalo",
    "Buffalo Gap",
    "Bula",
    "Bullard",
    "Bulverde",
    "Buna",
    "Burkburnett",
    "Burkett",
    "Burkeville",
    "Burleson",
    "Burlington",
    "Burnet",
    "Burton",
    "Bushland",
    "Byers",
    "Bynum",
    "Cactus",
    "Caddo",
    "Caddo Mills",
    "Caldwell",
    "Call",
    "Calliham",
    "Calvert",
    "Camden",
    "Cameron",
    "Camp Wood",
    "Campbell",
    "Campbellton",
    "Canadian",
    "Canton",
    "Canutillo",
    "Canyon",
    "Canyon Lake",
    "Carbon",
    "Carey",
    "Carlsbad",
    "Carlton",
    "Carmine",
    "Carrizo Springs",
    "Carrollton",
    "Carthage",
    "Cason",
    "Castell",
    "Castroville",
    "Cat Spring",
    "Catarina",
    "Cayuga",
    "Cedar Creek",
    "Cedar Hill",
    "Cedar Lane",
    "Cedar Park",
    "Cee Vee",
    "Celeste",
    "Celina",
    "Center",
    "Center Point",
    "Centerville",
    "Centralia",
    "Chalk",
    "Chandler",
    "Channelview",
    "Channing",
    "Chapman Ranch",
    "Chappell Hill",
    "Charlotte",
    "Chatfield",
    "Cherokee",
    "Chester",
    "Chico",
    "Chicota",
    "Childress",
    "Chillicothe",
    "Chilton",
    "China",
    "China Spring",
    "Chireno",
    "Chriesman",
    "Christine",
    "Christoval",
    "Cibolo",
    "Cisco",
    "Clarendon",
    "Clarksville",
    "Claude",
    "Clay",
    "Clayton",
    "Cleburne",
    "Cleveland",
    "Clifton",
    "Clint",
    "Clute",
    "Clyde",
    "Coahoma",
    "Coldspring",
    "Coleman",
    "College Station",
    "Collegeport",
    "Colleyville",
    "Collinsville",
    "Colmesneil",
    "Colorado City",
    "Columbus",
    "Comanche",
    "Combes",
    "Comfort",
    "Commerce",
    "Como",
    "Comstock",
    "Concan",
    "Concepcion",
    "Concord",
    "Conroe",
    "Converse",
    "Cookville",
    "Coolidge",
    "Cooper",
    "Copeville",
    "Coppell",
    "Copperas Cove",
    "Corinth",
    "Corpus Christi",
    "Corrigan",
    "Corsicana",
    "Cost",
    "Cotton Center",
    "Cotulla",
    "Coupland",
    "Covington",
    "Coyanosa",
    "Crandall",
    "Crane",
    "Cranfills Gap",
    "Crawford",
    "Cresson",
    "Crockett",
    "Crosby",
    "Crosbyton",
    "Cross Plains",
    "Crowell",
    "Crowley",
    "Crystal City",
    "Cuero",
    "Cumby",
    "Cuney",
    "Cunningham",
    "Cushing",
    "Cypress",
    "D Hanis",
    "Daingerfield",
    "Daisetta",
    "Dale",
    "Dalhart",
    "Dallardsville",
    "Dallas",
    "Damon",
    "Danbury",
    "Danciger",
    "Danevang",
    "Darrouzett",
    "Davilla",
    "Dawn",
    "Dawson",
    "Dayton",
    "De Berry",
    "De Kalb",
    "De Leon",
    "Deanville",
    "Decatur",
    "Deer Park",
    "Del Rio",
    "Del Valle",
    "Dell City",
    "Delmita",
    "Denison",
    "Dennis",
    "Denton",
    "Denver City",
    "Deport",
    "Desdemona",
    "Desoto",
    "Detroit",
    "Devers",
    "Devine",
    "Deweyville",
    "Diana",
    "Diboll",
    "Dickens",
    "Dickinson",
    "Dike",
    "Dilley",
    "Dime Box",
    "Dimmitt",
    "Dinero",
    "Dobbin",
    "Dodd City",
    "Dodge",
    "Dodson",
    "Donie",
    "Donna",
    "Doole",
    "Doss",
    "Doucette",
    "Dougherty",
    "Douglass",
    "Douglassville",
    "Driftwood",
    "Dripping Springs",
    "Driscoll",
    "Dryden",
    "Dublin",
    "Dumas",
    "Dumont",
    "Duncanville",
    "Dunn",
    "Dyess AFB",
    "Eagle Lake",
    "Eagle Pass",
    "Early",
    "Earth",
    "East Bernard",
    "Eastland",
    "Easton",
    "Ecleto",
    "Ector",
    "Edcouch",
    "Eddy",
    "Eden",
    "Edgewood",
    "Edinburg",
    "Edmonson",
    "Edna",
    "Edroy",
    "Egypt",
    "El Campo",
    "El Indio",
    "El Paso",
    "Eldorado",
    "Electra",
    "Elgin",
    "Elkhart",
    "Ellinger",
    "Elm Mott",
    "Elmaton",
    "Elmendorf",
    "Elmo",
    "Elsa",
    "Elysian Fields",
    "Emory",
    "Encinal",
    "Encino",
    "Energy",
    "Enloe",
    "Ennis",
    "Enochs",
    "Eola",
    "Era",
    "Estelline",
    "Etoile",
    "Euless",
    "Eustace",
    "Evadale",
    "Evant",
    "Fabens",
    "Fairfield",
    "Falcon Heights",
    "Falfurrias",
    "Falls City",
    "Fannin",
    "Farmersville",
    "Farnsworth",
    "Farwell",
    "Fate",
    "Fayetteville",
    "Fentress",
    "Ferris",
    "Fieldton",
    "Fischer",
    "Flat",
    "Flatonia",
    "Flint",
    "Flomot",
    "Florence",
    "Floresville",
    "Flower Mound",
    "Floydada",
    "Fluvanna",
    "Flynn",
    "Follett",
    "Forestburg",
    "Forney",
    "Forreston",
    "Forsan",
    "Fort Davis",
    "Fort Hancock",
    "Fort McKavett",
    "Fort Stockton",
    "Fort Worth",
    "Fowlerton",
    "Francitas",
    "Franklin",
    "Frankston",
    "Fred",
    "Fredericksburg",
    "Fredonia",
    "Freeport",
    "Freer",
    "Fresno",
    "Friendswood",
    "Friona",
    "Frisco",
    "Fritch",
    "Frost",
    "Fruitvale",
    "Fulshear",
    "Fulton",
    "Gail",
    "Gainesville",
    "Galena Park",
    "Gallatin",
    "Galveston",
    "Ganado",
    "Garciasville",
    "Garden City",
    "Gardendale",
    "Garland",
    "Garrison",
    "Garwood",
    "Gary",
    "Gatesville",
    "Gause",
    "Geneva",
    "George West",
    "Georgetown",
    "Geronimo",
    "Giddings",
    "Gilchrist",
    "Gillett",
    "Gilmer",
    "Girard",
    "Girvin",
    "Gladewater",
    "Glen Flora",
    "Glen Rose",
    "Glidden",
    "Gober",
    "Godley",
    "Golden",
    "Goldsboro",
    "Goldsmith",
    "Goldthwaite",
    "Goliad",
    "Gonzales",
    "Goodfellow AFB",
    "Goodrich",
    "Gordon",
    "Gordonville",
    "Goree",
    "Gorman",
    "Gouldbusk",
    "Graford",
    "Graham",
    "Granbury",
    "Grand Prairie",
    "Grand Saline",
    "Grandfalls",
    "Grandview",
    "Granger",
    "Grapeland",
    "Grapevine",
    "Greenville",
    "Greenwood",
    "Gregory",
    "Groesbeck",
    "Groom",
    "Groves",
    "Groveton",
    "Grulla",
    "Gruver",
    "Guerra",
    "Gun Barrel City",
    "Gunter",
    "Gustine",
    "Guthrie",
    "Guy",
    "Hale Center",
    "Hallettsville",
    "Hallsville",
    "Haltom City",
    "Hamilton",
    "Hamlin",
    "Hamshire",
    "Hankamer",
    "Happy",
    "Hardin",
    "Hargill",
    "Harker Heights",
    "Harleton",
    "Harlingen",
    "Harper",
    "Harrold",
    "Hart",
    "Hartley",
    "Harwood",
    "Haskell",
    "Haslet",
    "Hawkins",
    "Hawley",
    "Hearne",
    "Hebbronville",
    "Hedley",
    "Heidenheimer",
    "Helotes",
    "Hemphill",
    "Hempstead",
    "Henderson",
    "Henrietta",
    "Hereford",
    "Hermleigh",
    "Hewitt",
    "Hext",
    "Hico",
    "Hidalgo",
    "Higgins",
    "High Island",
    "Highlands",
    "Hillister",
    "Hillsboro",
    "Hitchcock",
    "Hobson",
    "Hochheim",
    "Hockley",
    "Holland",
    "Holliday",
    "Hondo",
    "Honey Grove",
    "Hooks",
    "Houston",
    "Howe",
    "Hubbard",
    "Huffman",
    "Hufsmith",
    "Hughes Springs",
    "Hull",
    "Humble",
    "Hungerford",
    "Hunt",
    "Huntington",
    "Huntsville",
    "Hurst",
    "Hutchins",
    "Hutto",
    "Hye",
    "Idalou",
    "Imperial",
    "Industry",
    "Inez",
    "Ingleside",
    "Ingram",
    "Iola",
    "Iowa Park",
    "Ira",
    "Iraan",
    "Iredell",
    "Irene",
    "Irving",
    "Italy",
    "Itasca",
    "Ivanhoe",
    "Jacksboro",
    "Jacksonville",
    "Jarrell",
    "Jasper",
    "Jayton",
    "Jefferson",
    "Jermyn",
    "Jewett",
    "Joaquin",
    "Johnson City",
    "Joinerville",
    "Jonesboro",
    "Jonesville",
    "Josephine",
    "Joshua",
    "Jourdanton",
    "Judson",
    "Junction",
    "Justiceburg",
    "Justin",
    "Kamay",
    "Karnack",
    "Karnes City",
    "Katy",
    "Kaufman",
    "Keene",
    "Keller",
    "Kemah",
    "Kemp",
    "Kempner",
    "Kendalia",
    "Kendleton",
    "Kenedy",
    "Kennard",
    "Kennedale",
    "Kenney",
    "Kerens",
    "Kermit",
    "Kerrville",
    "Kildare",
    "Kilgore",
    "Killeen",
    "Kingsbury",
    "Kingsland",
    "Kingsville",
    "Kirbyville",
    "Kirkland",
    "Kirvin",
    "Klondike",
    "Knickerbocker",
    "Knippa",
    "Knott",
    "Knox City",
    "Kopperl",
    "Kosse",
    "Kountze",
    "Kress",
    "Krum",
    "Kurten",
    "Kyle",
    "La Blanca",
    "La Coste",
    "La Feria",
    "La Grange",
    "La Joya",
    "La Marque",
    "La Porte",
    "La Pryor",
    "La Salle",
    "La Vernia",
    "La Victoria",
    "La Villa",
    "La Ward",
    "Ladonia",
    "Laguna Park",
    "Laird Hill",
    "Lake Creek",
    "Lake Dallas",
    "Lake Jackson",
    "Lakeview",
    "Lamesa",
    "Lampasas",
    "Lancaster",
    "Lane City",
    "Laneville",
    "Langtry",
    "Laredo",
    "Larue",
    "Lasara",
    "Latexo",
    "Laughlin A F B",
    "Lavon",
    "Lawn",
    "Lazbuddie",
    "League City",
    "Leakey",
    "Leander",
    "Ledbetter",
    "Leesburg",
    "Leesville",
    "Lefors",
    "Leggett",
    "Lelia Lake",
    "Leming",
    "Lenorah",
    "Leon Junction",
    "Leona",
    "Leonard",
    "Leroy",
    "Levelland",
    "Lewisville",
    "Lexington",
    "Liberty",
    "Liberty Hill",
    "Lillian",
    "Lincoln",
    "Lindale",
    "Linden",
    "Lindsay",
    "Lingleville",
    "Linn",
    "Lipan",
    "Lipscomb",
    "Lissie",
    "Little Elm",
    "Little River",
    "Littlefield",
    "Liverpool",
    "Livingston",
    "Llano",
    "Lockhart",
    "Lockney",
    "Lodi",
    "Lohn",
    "Lolita",
    "Lometa",
    "London",
    "Lone Oak",
    "Lone Star",
    "Long Branch",
    "Long Mott",
    "Longview",
    "Loop",
    "Lopeno",
    "Loraine",
    "Lorena",
    "Lorenzo",
    "Los Ebanos",
    "Los Fresnos",
    "Los Indios",
    "Lott",
    "Louise",
    "Lovelady",
    "Loving",
    "Lowake",
    "Lozano",
    "Lubbock",
    "Lueders",
    "Lufkin",
    "Luling",
    "Lumberton",
    "Lyford",
    "Lyons",
    "Lytle",
    "Mabank",
    "Macdona",
    "Madisonville",
    "Magnolia",
    "Malakoff",
    "Malone",
    "Manchaca",
    "Manor",
    "Mansfield",
    "Manvel",
    "Maple",
    "Marathon",
    "Marble Falls",
    "Marfa",
    "Marietta",
    "Marion",
    "Markham",
    "Marlin",
    "Marquez",
    "Marshall",
    "Mart",
    "Martindale",
    "Martinsville",
    "Maryneal",
    "Mason",
    "Masterson",
    "Matador",
    "Matagorda",
    "Mathis",
    "Maud",
    "Mauriceville",
    "Maxwell",
    "May",
    "Maydelle",
    "Maypearl",
    "Maysfield",
    "Mcadoo",
    "McAllen",
    "McCamey",
    "McCaulley",
    "McCoy",
    "McDade",
    "Mcfaddin",
    "McGregor",
    "McKinney",
    "Mclean",
    "McLeod",
    "McNeil",
    "McQueeney",
    "Meadow",
    "Medina",
    "Megargel",
    "Melissa",
    "Melvin",
    "Memphis",
    "Menard",
    "Mentone",
    "Mercedes",
    "Mereta",
    "Meridian",
    "Merit",
    "Merkel",
    "Mertens",
    "Mertzon",
    "Mesquite",
    "Mexia",
    "Meyersville",
    "Miami",
    "Mico",
    "Midfield",
    "Midkiff",
    "Midland",
    "Midlothian",
    "Midway",
    "Milam",
    "Milano",
    "Miles",
    "Milford",
    "Millersview",
    "Millican",
    "Millsap",
    "Minden",
    "Mineola",
    "Mineral",
    "Mineral Wells",
    "Mingus",
    "Mirando City",
    "Mission",
    "Missouri City",
    "Mobeetie",
    "Monahans",
    "Mont Belvieu",
    "Montague",
    "Montalba",
    "Montgomery",
    "Moody",
    "Moore",
    "Moran",
    "Morgan",
    "Morgan Mill",
    "Morse",
    "Morton",
    "Moscow",
    "Moulton",
    "Mound",
    "Mount Calm",
    "Mount Enterprise",
    "Mount Pleasant",
    "Mount Vernon",
    "Mountain Home",
    "Muenster",
    "Muldoon",
    "Muleshoe",
    "Mullin",
    "Mumford",
    "Munday",
    "Murchison",
    "Myra",
    "Nacogdoches",
    "Nada",
    "Naples",
    "Nash",
    "Natalia",
    "Naval Air Station/ Jrb",
    "Navasota",
    "Nazareth",
    "Neches",
    "Nederland",
    "Needville",
    "Nemo",
    "Nevada",
    "New Baden",
    "New Boston",
    "New Braunfels",
    "New Caney",
    "New Deal",
    "New Home",
    "New London",
    "New Summerfield",
    "New Ulm",
    "New Waverly",
    "Newark",
    "Newcastle",
    "Newgulf",
    "Newton",
    "Nixon",
    "Nocona",
    "Nolan",
    "Nolanville",
    "Nome",
    "Nordheim",
    "Normangee",
    "Normanna",
    "North Houston",
    "North Richland Hills",
    "North Zulch",
    "Norton",
    "Notrees",
    "Novice",
    "Nursery",
    "O Brien",
    "Oakhurst",
    "Oakland",
    "Oakville",
    "Oakwood",
    "Odell",
    "Odem",
    "Odessa",
    "Odonnell",
    "Oglesby",
    "Oilton",
    "Oklaunion",
    "Old Glory",
    "Old Ocean",
    "Olden",
    "Olmito",
    "Olney",
    "Olton",
    "Omaha",
    "Onalaska",
    "Orange",
    "Orange Grove",
    "Orangefield",
    "Orchard",
    "Ore City",
    "Orla",
    "Ottine",
    "Otto",
    "Ovalo",
    "Overton",
    "Ozona",
    "Paducah",
    "Paige",
    "Paint Rock",
    "Palacios",
    "Palestine",
    "Palmer",
    "Palo Pinto",
    "Paluxy",
    "Pampa",
    "Pandora",
    "Panhandle",
    "Panna Maria",
    "Panola",
    "Paradise",
    "Paris",
    "Pasadena",
    "Pattison",
    "Pattonville",
    "Pawnee",
    "Pear Valley",
    "Pearland",
    "Pearsall",
    "Peaster",
    "Pecan Gap",
    "Pecos",
    "Peggy",
    "Pendleton",
    "Penelope",
    "Penitas",
    "Pennington",
    "Penwell",
    "Pep",
    "Perrin",
    "Perry",
    "Perryton",
    "Petersburg",
    "Petrolia",
    "Pettus",
    "Petty",
    "Pflugerville",
    "Pharr",
    "Pickton",
    "Pierce",
    "Pilot Point",
    "Pinehurst",
    "Pineland",
    "Pipe Creek",
    "Pittsburg",
    "Placedo",
    "Plains",
    "Plainview",
    "Plano",
    "Plantersville",
    "Pleasanton",
    "Pledger",
    "Plum",
    "Point",
    "Point Comfort",
    "Pointblank",
    "Pollok",
    "Ponder",
    "Pontotoc",
    "Poolville",
    "Port Aransas",
    "Port Arthur",
    "Port Bolivar",
    "Port Isabel",
    "Port Lavaca",
    "Port Mansfield",
    "Port Neches",
    "Port O Connor",
    "Porter",
    "Portland",
    "Post",
    "Poteet",
    "Poth",
    "Pottsboro",
    "Pottsville",
    "Powderly",
    "Powell",
    "Poynor",
    "Prairie Hill",
    "Prairie Lea",
    "Prairie View",
    "Premont",
    "Presidio",
    "Price",
    "Priddy",
    "Princeton",
    "Proctor",
    "Progreso",
    "Prosper",
    "Purdon",
    "Purmela",
    "Putnam",
    "Pyote",
    "Quail",
    "Quanah",
    "Queen City",
    "Quemado",
    "Quinlan",
    "Quitaque",
    "Quitman",
    "Rainbow",
    "Ralls",
    "Rancho Alegre",
    "Randolph",
    "Ranger",
    "Rankin",
    "Ransom Canyon",
    "Ratcliff",
    "Ravenna",
    "Raymondville",
    "Raywood",
    "Reagan",
    "Realitos",
    "Red Oak",
    "Red Rock",
    "Redford",
    "Redwater",
    "Refugio",
    "Reklaw",
    "Rhome",
    "Rice",
    "Richards",
    "Richardson",
    "Richland",
    "Richland Springs",
    "Richmond",
    "Riesel",
    "Ringgold",
    "Rio Frio",
    "Rio Grande City",
    "Rio Hondo",
    "Rio Medina",
    "Rio Vista",
    "Rising Star",
    "Riverside",
    "Riviera",
    "Roanoke",
    "Roans Prairie",
    "Roaring Springs",
    "Robert Lee",
    "Robstown",
    "Roby",
    "Rochelle",
    "Rochester",
    "Rock Island",
    "Rockdale",
    "Rockport",
    "Rocksprings",
    "Rockwall",
    "Rockwood",
    "Rogers",
    "Roma",
    "Romayor",
    "Roosevelt",
    "Ropesville",
    "Rosanky",
    "Roscoe",
    "Rosebud",
    "Rosenberg",
    "Rosharon",
    "Ross",
    "Rosser",
    "Rosston",
    "Rotan",
    "Round Mountain",
    "Round Rock",
    "Round Top",
    "Rowena",
    "Rowlett",
    "Roxton",
    "Royalty",
    "Royse City",
    "Rule",
    "Runge",
    "Rusk",
    "Rye",
    "Sabinal",
    "Sabine Pass",
    "Sacul",
    "Sadler",
    "Saint Hedwig",
    "Saint Jo",
    "Salado",
    "Salineno",
    "Salt Flat",
    "Saltillo",
    "Samnorwood",
    "San Angelo",
    "San Antonio",
    "San Augustine",
    "San Benito",
    "San Diego",
    "San Elizario",
    "San Felipe",
    "San Isidro",
    "San Juan",
    "San Leon",
    "San Marcos",
    "San Perlita",
    "San Saba",
    "San Ygnacio",
    "Sanderson",
    "Sandia",
    "Sandy",
    "Sanford",
    "Sanger",
    "Santa Anna",
    "Santa Elena",
    "Santa Fe",
    "Santa Maria",
    "Santa Rosa",
    "Santo",
    "Saragosa",
    "Saratoga",
    "Sarita",
    "Satin",
    "Savoy",
    "Schertz",
    "Schulenburg",
    "Schwertner",
    "Scotland",
    "Scottsville",
    "Scroggins",
    "Scurry",
    "Seabrook",
    "Seadrift",
    "Seagoville",
    "Seagraves",
    "Sealy",
    "Sebastian",
    "Seguin",
    "Selman City",
    "Seminole",
    "Seymour",
    "Shafter",
    "Shallowater",
    "Shamrock",
    "Sheffield",
    "Shelbyville",
    "Shepherd",
    "Sheppard AFB",
    "Sheridan",
    "Sherman",
    "Shiner",
    "Shiro",
    "Sidney",
    "Sienna Plantation",
    "Sierra Blanca",
    "Silsbee",
    "Silver",
    "Silverton",
    "Simms",
    "Simonton",
    "Sinton",
    "Skellytown",
    "Skidmore",
    "Slaton",
    "Slidell",
    "Smiley",
    "Smithville",
    "Smyer",
    "Snook",
    "Snyder",
    "Somerset",
    "Somerville",
    "Sonora",
    "Sour Lake",
    "South Bend",
    "South Houston",
    "South Padre Island",
    "South Plains",
    "Southlake",
    "Southmayd",
    "Spade",
    "Speaks",
    "Spearman",
    "Spicewood",
    "Splendora",
    "Spring",
    "Spring Branch",
    "Springlake",
    "Springtown",
    "Spur",
    "Spurger",
    "Stafford",
    "Stamford",
    "Stanton",
    "Staples",
    "Star",
    "Stephenville",
    "Sterling City",
    "Stinnett",
    "Stockdale",
    "Stonewall",
    "Stowell",
    "Stratford",
    "Strawn",
    "Streetman",
    "Sublime",
    "Sudan",
    "Sugar Land",
    "Sullivan City",
    "Sulphur Bluff",
    "Sulphur Springs",
    "Summerfield",
    "Sumner",
    "Sundown",
    "Sunnyvale",
    "Sunray",
    "Sunset",
    "Sutherland Springs",
    "Sweeny",
    "Sweet Home",
    "Sweetwater",
    "Sylvester",
    "Taft",
    "Tahoka",
    "Talco",
    "Talpa",
    "Tarpley",
    "Tarzan",
    "Tatum",
    "Taylor",
    "Teague",
    "Tehuacana",
    "Telegraph",
    "Telephone",
    "Telferner",
    "Tell",
    "Temple",
    "Tenaha",
    "Tennessee Colony",
    "Tennyson",
    "Terlingua",
    "Terrell",
    "Texarkana",
    "Texas City",
    "Texline",
    "The Colony",
    "Thicket",
    "Thomaston",
    "Thompsons",
    "Thorndale",
    "Thornton",
    "Thrall",
    "Three Rivers",
    "Throckmorton",
    "Tilden",
    "Timpson",
    "Tioga",
    "Tivoli",
    "Tokio",
    "Tolar",
    "Tom Bean",
    "Tomball",
    "Tornillo",
    "Tow",
    "Toyah",
    "Toyahvale",
    "Trent",
    "Trenton",
    "Trinidad",
    "Trinity",
    "Troup",
    "Troy",
    "Tuleta",
    "Tulia",
    "Turkey",
    "Tuscola",
    "Tye",
    "Tyler",
    "Tynan",
    "Umbarger",
    "Universal City",
    "Utopia",
    "Uvalde",
    "Valentine",
    "Valera",
    "Valley Mills",
    "Valley Spring",
    "Valley View",
    "Van",
    "Van Alstyne",
    "Van Horn",
    "Van Vleck",
    "Vancourt",
    "Vanderbilt",
    "Vanderpool",
    "Vega",
    "Venus",
    "Veribest",
    "Vernon",
    "Victoria",
    "Vidor",
    "Village Mills",
    "Voca",
    "Von Ormy",
    "Voss",
    "Votaw",
    "Voth",
    "Waco",
    "Wadsworth",
    "Waelder",
    "Waka",
    "Walburg",
    "Wall",
    "Waller",
    "Wallis",
    "Wallisville",
    "Walnut Springs",
    "Warda",
    "Waring",
    "Warren",
    "Washington",
    "Waskom",
    "Water Valley",
    "Waxahachie",
    "Wayside",
    "Weatherford",
    "Webster",
    "Weesatche",
    "Weimar",
    "Weinert",
    "Weir",
    "Welch",
    "Wellborn",
    "Wellington",
    "Wellman",
    "Wells",
    "Weslaco",
    "West",
    "West Columbia",
    "West Point",
    "Westbrook",
    "Westhoff",
    "Westminster",
    "Weston",
    "Wharton",
    "Wheeler",
    "Wheelock",
    "White Deer",
    "White Oak",
    "Whiteface",
    "Whitehouse",
    "Whitesboro",
    "Whitewright",
    "Whitharral",
    "Whitney",
    "Whitsett",
    "Whitt",
    "Wichita Falls",
    "Wickett",
    "Wiergate",
    "Wildorado",
    "Willis",
    "Willow City",
    "Wills Point",
    "Wilmer",
    "Wilson",
    "Wimberley",
    "Windom",
    "Windthorst",
    "Winfield",
    "Wingate",
    "Wink",
    "Winnie",
    "Winnsboro",
    "Winona",
    "Winters",
    "Woden",
    "Wolfe City",
    "Wolfforth",
    "Woodlake",
    "Woodlawn",
    "Woodsboro",
    "Woodson",
    "Woodville",
    "Woodway",
    "Wortham",
    "Wrightsboro",
    "Wylie",
    "Yancey",
    "Yantis",
    "Yoakum",
    "Yorktown",
    "Zapata",
    "Zavalla",
    "Zephyr"
];

var datalist = document.getElementById("cities");

validCities.forEach(function(city) {
    var option = document.createElement("option");
    option.value = city;
    datalist.appendChild(option);
});

function validateFlights() {
    var originCity = document.getElementById("flightOriginCity").value.trim();
    var destinationCity = document.getElementById("flightDestinationCity").value.trim();
    var departure = new Date(document.getElementById("flightDeparture").value);
    var adults = document.getElementById("flightAdults").value.trim();
    var children = document.getElementById("flightChildren").value.trim();
    var infants = document.getElementById("flightInfants").value.trim();

    const earliestDate = new Date("2024-09-01");
    const latestDate = new Date("2024-12-01");

    if (!validCities.includes(originCity) || !validCities.includes(destinationCity)) {
        return alert("Cities must be in Texas or California.");
    } else if (departure < earliestDate || departure > latestDate) {
        return alert("Departure date must be between Sep 1, 2024 and Dec 1, 2024.");
    } else if (adults.match(/^$/) || children.match(/^$/) || infants.match(/^$/)) {
        return alert("Must enter a number for adults, children, and infants.");
    } else if (adults.match(/0/)) {
        return alert("Must have at least one adult.");
    } else if (!adults.match(/[1-4]/) || !children.match(/[0-4]/) || !infants.match(/[0-4]/)) {
        return alert("Cannot have more than 4 passengers of one type.");
    }
    
    var resultString = `Flight booked: ${originCity} to ${destinationCity} departing ${departure.toDateString()} with seats for ${adults} adults, ${children} children, and ${infants} infants.`
    
    document.getElementById("flightResult").innerHTML = resultString;
}

$(function() {
    // Toggle form when pressing passenger icon
    $("#passengerIcon").on("click", function() {
        $("#flightForm").fadeToggle();
    });
});